### ISSUE TITLE
Examples of using `context`?

### ISSUE THREAD

**Issue by dnikolovv** [robertdp/purescript-react-halo#13]
First of all, thanks for the great library.

I've been messing around with it but there's one thing that I can't understand and that is how are you supposed to use the `context`?

I presume it refers to https://reactjs.org/docs/context.html, but couldn't quite figure out how to combine the two.

**Comment by robertdp** [comment]
Hi @dnikolovv,

Contexts here are somewhat related, in that it's intended to provide a way to pass down some value that's derived from React hook lifecycles without the boilerplate of manual passing. It also works differently when using it with `Halo.component` versus `Halo.useHalo`.

```purescript
mkCurrentUserPosts = Halo.component { context, initialState, eval, render }
  where
  context props = React.do
    user <- React.useContext currentUserContext
    pure { user }  -- use any hooks to build a "context" value, which is then available throughout the component

  initialState props ctx =
    { userId: ctx.user.id  -- available when creating the initial component state
    , posts: RemoteData.NotAsked
    }

  onAction = case _ of
    Load -> do
      { user } <- Halo.context  -- available to be read at any time
      State.modify_ _ { userId = user.id, posts = RemoteData.Loading }
      posts <- fetchPostsForUser user.id
      { userId } <- State.get
      when (userId == user.id) do
        State.modify_ _ { posts = RemoteData.Success posts }
    Refresh -> do
      { user } <- Halo.context  -- subsequent reads can return different values (hook lifecycles update the context value)
      { userId } <- State.get
      when (userId /= user.id) do
        onAction Load

  eval = mkEval _
    { onInitialize = \_ -> Just Load
    , onUpdate = \_ _ -> Just Refresh
    , onAction
    }

  render ...
```

Manual passing is more explicit, and I can't remember what originally motivated me to add this feature except that I wanted to produce a value from some arbitrary hook-based logic and then use it elsewhere in the component.

**Comment by robertdp** [comment]
There's a decent argument to be made that this is an anti-pattern because it runs against composability. 🙂

**Comment by robertdp** [comment]
I've removed this awkward idea of contexts from the lib and bumped the version to v3. This has been added back to the package set as well.

Something similar should be achievable with the `useHalo` hook, if required.

**Comment by dnikolovv** [comment]
Hey @robertdp and thanks for the quick reply!

Haha, damn, when I tried using it it seems I had forgotten to put in `React.do` instead of just `do`. Anyways, glad that this resulted in a library cleanup.

Will be closing this issue.
